FROM fedora:rawhide

RUN dnf install -y \
	tpm2-tss-devel-4.1.3-10 tpm2-tools \
	swtpm swtpm-tools swtpm-selinux\
	rust clippy cargo \
	llvm llvm-devel clang pkg-config \
	dbus-daemon rust-gobject-sys-devel
